Calculate body weight
scream-4/CalculateBodyWeight pull request #1
Opened 2022-07-26 09:17 UTC by scream-4

Homework les 5

2022-07-26 09:29 UTC, scream-4 commented
les5

2022-07-27 06:18 UTC, khadasevich requested changes
Also please add .gitignore file and don't store .idea and target directories

2022-07-27 06:18 UTC, khadasevich commented on BodyWeightCalculator/src/test/java/TestCalculate.java
> +    public void SetUp() {
please follow Java Naming Convention https://comaqa.gitbook.io/java-automation/stil-napisaniya-koda/konvenciya-imenovaniya#:~:text=%D0%9A%D0%BE%D0%BD%D0%B2%D0%B5%D0%BD%D1%86%D0%B8%D1%8F%20%D0%B8%D0%BC%D0%B5%D0%BD%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%20%2D%20Java%20%D0%B4%D0%BB%D1%8F%20%D0%B0%D0%B2%D1%82%D0%BE%D0%BC%D0%B0%D1%82%D0%B8%D0%B7%D0%B0%D1%82%D0%BE%D1%80%D0%BE%D0%B2&text=%D0%9A%D0%BE%D0%BD%D0%B2%D0%B5%D0%BD%D1%86%D0%B8%D1%8F%20%D0%B8%D0%BC%D0%B5%D0%BD%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%20%D0%B4%D0%B5%D0%BB%D0%B0%D0%B5%D1%82%20%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%83%20%D0%B1%D0%BE%D0%BB%D0%B5%D0%B5,%D0%B1%D1%8B%D1%82%D1%8C%20%D0%BF%D0%BE%D0%BB%D0%B5%D0%B7%D0%BD%D1%8B%D0%BC%20%D0%B2%20%D0%BF%D0%BE%D0%BD%D0%B8%D0%BC%D0%B0%D0%BD%D0%B8%D0%B8%20%D0%BA%D0%BE%D0%B4%D0%B0.

2022-07-27 06:18 UTC, khadasevich commented on BodyWeightCalculator/src/test/java/TestCalculate.java
> +public class TestCalculate {
Test classes should end by Test word

2022-07-27 06:18 UTC, khadasevich commented on BodyWeightCalculator/src/test/java/TestCalculate.java
> +    private void InputWeightHeight(String weight, String height) {
Please follow naming convention

2022-07-27 06:18 UTC, khadasevich commented on BodyWeightCalculator/src/test/java/TestCalculate.java
> +    }
Please follow naming convention + test method should end by Test + Test without assertion it's just list of steps

2022-07-27 06:18 UTC, khadasevich commented on BodyWeightCalculator/src/test/java/TestCalculate.java
> +    @Test
See comment above

2022-07-27 06:18 UTC, khadasevich commented on BodyWeightCalculator/src/test/java/TestCalculate.java
> +    public void UnderWeight() {
See comment above

2022-07-27 06:18 UTC, khadasevich commented on BodyWeightCalculator/src/test/java/TestCalculate.java
> +    public void Starvation() {
See comment above

2022-07-27 06:18 UTC, khadasevich commented on BodyWeightCalculator/src/test/java/TestCalculate.java
> +    public void Obese() {
See comment above

2022-08-02 14:34 UTC, khadasevich approved these changes

2022-08-02 14:35 UTC, merged